---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:3bca6923ad0f2fccf76fbd43bec71376d517b12ebe82d7ef5408ea5396613d19
dependencies:
  ansible_core:
    package_pip: ansible-core==2.16.6
  ansible_runner:
    package_pip: ansible-runner==2.3.6
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
  system: |
    git-core [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    gzip [platform:rpm]
    tar [platform:rpm]
    openssh [platform:rpm]
options:
  package_manager_path: /usr/bin/microdnf
additional_build_steps:
  append_final:
    - RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
    - RUN curl -L https://mirror.openshift.com/pub/openshift-v4/clients/helm/latest/helm-linux-amd64 -o /usr/local/bin/helm && chmod +x /usr/local/bin/helm
