---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:eb937c2543c5c7d5efd0699e66ecbff4054a1051e16bda8f2b2c55954faac107
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.4
  ansible_runner:
    package_pip: ansible-runner==2.3.4
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf
