---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:6e1ace030fa2ef5c72a72d5eb63a348607e114399c8badb4bf58d9f7d5aff71b
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.5
  ansible_runner:
    package_pip: ansible-runner==2.3.4
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf
