---
version: 3

images:
  base_image:
    name: quay.io/fedora/fedora:39@sha256:ffe14fd578df4046db334ff9a32cf2e1ad704abd4877912f33c9d1b3fe0995dc
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.1
  ansible_runner:
    package_pip: ansible-runner==2.3.3
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
