---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:f85c7d635158f2044cfdf832a04081dd2eace04ff94dfeea1259c11fccffe5b6
dependencies:
  ansible_core:
    package_pip: ansible-core==2.16.3
  ansible_runner:
    package_pip: ansible-runner==2.3.4
  python_interpreter:
    package_system: "python39"
    python_path: "/usr/bin/python3"
  galaxy: requirements.yml
  python: requirements.txt
  system: |
    git-core [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    gzip [platform:rpm]
    tar [platform:rpm]
    openssh [platform:rpm]
options:
  package_manager_path: /usr/bin/microdnf
additional_build_steps:
  append_final:
#    - RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1
    - RUN curl -L https://mirror.openshift.com/pub/openshift-v4/clients/helm/latest/helm-linux-amd64 -o /usr/local/bin/helm && chmod +x /usr/local/bin/helm
