---
version: 3

images:
  base_image:
    name: quay.io/fedora/fedora:39@sha256:0f8fc0d1c23b63cee055cbb285c10f88b3ea9a427289a5a04932268618199ac8
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.1
  ansible_runner:
    package_pip: ansible-runner==2.3.3
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
