---
version: 3

images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:584e7946792c80a34b8b9c578ce88e84bd96d3b59e55e3c723dc0f0027096af8
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.3
  ansible_runner:
    package_pip: ansible-runner==2.3.3
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf
