---
version: 3
images:
  base_image:
    name: quay.io/ansible/awx-ee:22.3.0
dependencies:
  ansible_core:
    # renovate: datasource=pypi depName=ansible-core
    package_pip: ansible-core==2.15.0
  ansible_runner:
    package_pip: ansible-runner
  galaxy: requirements.yml
  python: requirements.txt
