---
version: 3

images:
  base_image:
    name: registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:1b6d711648229a1c987f39cfdfccaebe2bd92d0b5d8caa5dbaa5234a9278a0b2

dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.3
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  python: requirements.txt
  system: |
    git-core [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    gzip [platform:rpm]
    tar [platform:rpm]
    openssh [platform:rpm]

options:
  package_manager_path: /usr/bin/microdnf
