---
version: 3

images:
  base_image:
    name: registry.access.redhat.com/ubi9/ubi-minimal:latest@sha256:35c99977ee5baa359bdc80f9ccc360644d2dbccb7462ca0fd97a23170a00cfd1

dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.2
  ansible_runner:
    package_pip: ansible-runner==2.3.3
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  python: requirements.txt
  system: |
    git-core [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    gzip [platform:rpm]
    tar [platform:rpm]
    openssh [platform:rpm]

options:
  package_manager_path: /usr/bin/microdnf
