---
version: 3

dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.0
  ansible_runner:
    package_pip: ansible-runner==2.3.3
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  python: requirements.txt
  system: |
    git-core [platform:rpm]
    sshpass [platform:rpm]
    rsync [platform:rpm]
    gzip [platform:rpm]
    tar [platform:rpm]
    openssh [platform:rpm]

images:
  base_image:
    name: registry.access.redhat.com/ubi9/ubi-minimal:9.2-484@sha256:6b114b624088a32d69f1dcc95a2bf8a6393d08b0f6316cf1c42c6e0b01e1870a

options:
  package_manager_path: /usr/bin/microdnf
