---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:1ba6756f11380a44ad42241f6781a047b949ace6880e52ec7aaf1f70c995524c
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.2
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
