---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:198813dbb52a859aaa4fc9666a2c21e952a8c17ad8f8d3946ef65f91585cbfbf
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.1
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
