---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:ac7a5f16b9ae56e53da9873e6e569839236164918ca214f7cfae92a27d0998a9
dependencies:
  ansible_core:
    package_pip: ansible-core==2.16.2
  ansible_runner:
    package_pip: ansible-runner==2.3.4
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
