---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:103566b63045bb183939f41e76ce8cdac03e298ade8cdb51fd724973ba7aed17
dependencies:
  ansible_core:
    package_pip: ansible-core==2.16.2
  ansible_runner:
    package_pip: ansible-runner==2.3.4
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
