---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:427c79d1b56f1edb1f5aa8e6a3acfa6f9b2cc0a5914a30f4bf9668d7b4d6e9af
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.5
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
