---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:7ab67cd89b5cfada30e99b18d5cabdffea798231b9cc432c95ca4b178510c7d1
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.0
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
