---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:776775e0be771028494356f22ed911265f56bbdac43cc807b58b02c03085de9c
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.0
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
