---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:9457217ff28852e970608f365bd830702c9f1023c049b4f1852fbb98b6ae8e06
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.2
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
