---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:089e44eb42f1bdc4a18cf58b598f590720c5ec7710a565b0a8a2b9da42c15b55
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.0
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
