---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:b4f27428b33d0e378c00f8f7112fdca3af9d690488cfcffa3b5c9b31fe82d788
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.0
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
