---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:e3d9a81d139715b5f7319c1a4d2c3eb25810821ec0c61b565457e9e578fe9463
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.0
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
