---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:44c20dc2ced050ca373a21764f5044b0b537f81e7f0e10ccd910467ef1a7a024
dependencies:
  ansible_core:
    package_pip: ansible-core==2.16.0
  ansible_runner:
    package_pip: ansible-runner==2.3.4
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
