---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:f6af8c0489a46e241454d02d952061d7c3058559d7c367d68d2cd64fc312bfbb
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.0
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
