---
collections:
  - name: ansible.netcommon
    version: 5.1.2
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 7.1.0
  - name: freeipa.ansible_freeipa
    version: 1.11.0
  - name: hetzner.hcloud
    version: 1.15.0
  - name: containers.podman
    version: 1.10.2
roles:
  - name: geerlingguy.ntp
