---
collections:
  - name: ansible.netcommon
    version: 5.3.0
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 8.0.2
  - name: freeipa.ansible_freeipa
    version: 1.11.1
  - name: hetzner.hcloud
    version: 2.4.0
  - name: containers.podman
    version: 1.11.0
roles:
  - name: geerlingguy.ntp
