---
collections:
  - name: ansible.netcommon
    version: 7.1.0
  - name: ansible.posix
    version: 1.6.0
  - name: community.general
    version: 8.3.0
  - name: freeipa.ansible_freeipa
    version: 1.13.2
  - name: hetzner.hcloud
    version: 4.2.1
  - name: containers.podman
    version: 1.16.0
roles:
  - name: geerlingguy.ntp
