---
collections:
  - name: ansible.netcommon
    version: 7.0.0
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 8.3.0
  - name: freeipa.ansible_freeipa
    version: 1.13.2
  - name: hetzner.hcloud
    version: 3.1.1
  - name: containers.podman
    version: 1.15.4
roles:
  - name: geerlingguy.ntp
