---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:3e8584ab12dbdb911289a5a6a06111b1df0873be47632f405c7d238e7553a393
dependencies:
  ansible_core:
    package_pip: ansible-core==2.16.0
  ansible_runner:
    package_pip: ansible-runner==2.3.4
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf