---
version: 3
images:
  base_image:
    name: quay.io/fedora/fedora:39@sha256:ff110340ba243b3892e32bb5877290c86d7f7939ebf82cd87cba254c272f2c6b
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.0
  ansible_runner:
    package_pip: ansible-runner==2.3.3
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
