---
version: 3
images:
  base_image:
    name: quay.io/fedora/fedora:39@sha256:57fc3d1b3be881d27ae3a3275b1ca2515d6dd0c48925b1a05b156a5859ed9a02
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.0
  ansible_runner:
    package_pip: ansible-runner==2.3.3
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
