---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:2b1e5dc4c9c0a6d4ad5c28590f57640b1822aec62a649bbcec0fd0025e7e782e
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.0
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf