---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:7a123fbf5e5c05d995828595056550166b9a95c8c93b7ea5920a24e027df31e5
dependencies:
  ansible_core:
    package_pip: ansible-core==2.16.6
  ansible_runner:
    package_pip: ansible-runner==2.3.6
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf