---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:a6cb9fa52d60cb3dec2b812caf345dc4ce3942e03f1d3ce06d83121053030fd8
dependencies:
  ansible_core:
    package_pip: ansible-core==2.16.1
  ansible_runner:
    package_pip: ansible-runner==2.3.4
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf