---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:cdfab8930d1006613f0d0d74010bf8634db0f32a54b8ee1e59f4f8d67395e5b6
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.4
  ansible_runner:
    package_pip: ansible-runner==2.3.4
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf