---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:574b99eeddf38221cd10fdee178f4083ce6330e1a5bf1a78fc36213428257dc3
dependencies:
  ansible_core:
    package_pip: ansible-core==2.16.2
  ansible_runner:
    package_pip: ansible-runner==2.3.4
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf