---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:8fbcc4e99328e3cb9ec2d52eaeb1d53bedfd5c504d4d84fbd0513481281efd0e
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.0
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf