---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:1644ea194109d0098e4f0cdc1a6a5beec99611480dd58104883fdd5131d0698f
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.1
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf