---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:2d1d54e76a5fffce0d7b7d5842b41b715fb0cb153ba85d3ddd71f2b005d5ab94
dependencies:
  ansible_core:
    package_pip: ansible-core==2.16.5
  ansible_runner:
    package_pip: ansible-runner==2.3.6
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf