---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:b6d9a513688e009f526ab2021056b2e65b8970b0ce323da7a9627043bc2e9c74
dependencies:
  ansible_core:
    package_pip: ansible-core==2.16.5
  ansible_runner:
    package_pip: ansible-runner==2.3.6
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf