---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:2c7b358086283b10015477a0e6b158257f0de080398c7ed2a35318cbb99986c6
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.4
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf