---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:92960412810491984291979d87a2927d264b71dda62a0405d7c1758238d54afb
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.1
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf