---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:367df42668011316043b59e0cd48fe2174554c88287f0997d5a8a2f49e3e6f42
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.4
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf