---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:162745ffd8dda767466ffc2c9752a21a9b3564fd7c13b3f6210fbc50c9fbd99c
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.1
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf