---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:45a91f4d6f88db77367fc474309ed18ec29d8fe7dc33f0880272820913ab56f2
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.4
  ansible_runner:
    package_pip: ansible-runner==2.3.4
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf