---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:bb7e163b89a29e3425d98e2bb1a79b051d0d85ed7c1bc161a619951070e80cca
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.2
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf