---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:e3042e1ca03a4e9ca06b608f69045e6f2f8d882a73dadc8af543f9d79ab736a1
dependencies:
  ansible_core:
    package_pip: ansible-core==2.16.4
  ansible_runner:
    package_pip: ansible-runner==2.3.6
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf