---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:853cf930beb2e1204223847f7e29b55a29c80feba081caa724dd4a0ce2532e61
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.5
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf