---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:e4c8791e3059a36fd44d907084c9ededfa4eec07c23a98d08ee88d79ab49fc26
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.1
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf