---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:850436bc58aa8959d655b67a9050ec7a7340101ca88253370ec64f94d02c1b6a
dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.1
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf