---
version: 3
images:
  base_image:
    name: quay.io/fedora/fedora:39@sha256:a30deaf3809a39b80ab227b5a4c93fb1974be2e783c5207c08b5312f8fa003ac
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.2
  ansible_runner:
    package_pip: ansible-runner==2.3.3
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
