---
version: 3
images:
  base_image:
    name: quay.io/centos/centos:stream9-minimal@sha256:685ea6772d51014e6fe1b068abf92a406d6e5ed9f84e6688990f8ba97d8ba48a
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.3
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    package_system: "python311"
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt
options:
  package_manager_path: /usr/bin/microdnf