---
version: 3
images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:a642f346e1645b884ddac1d68ea2efd34612f9aec812960deb22816d3047c067
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.0
  ansible_runner:
    package_pip: ansible-runner==2.3.3
  galaxy: requirements.yml
  python: requirements.txt
