---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:cfe29eab4dbcac0c0fb1e8bcdb077cf70a452d6bddfbb0411b1951caddeb556e
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.4
  ansible_runner:
    package_pip: ansible-runner==2.3.4
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
