---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:7097fbf52a7056b1b2f3559f1c6d11d12773664c0b906d3721634e82a07e079c
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.2
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
