---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:846f84360da8bd119b0e772806f874a2011a9c89e5f402fc4de5cc660c48be8a
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.2
  ansible_runner:
    package_pip: ansible-runner==2.3.3
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
