---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:834a9790b22e4c42152f428d28ac5785e6721d931dcb4791b75972472b7d94dc
dependencies:
  ansible_core:
    package_pip: ansible-core==2.16.6
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
