---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:2eaab492cb6e385b2a0a810f49f93c91da1c461488b6abd5ef4a51276278457e
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.5
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
