---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:475dc826e9f2fe9ef31d9da748df696749a5c2fe9d4be4c05c19b4f197853e00
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.3
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
