---
version: 3
images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:2b5689e53ef72fb7c67cd4180f3bbf49970c75a99d293b1a0d591aec87cda4d2
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.0
  ansible_runner:
    package_pip: ansible-runner==2.3.3
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
