---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:7d8b4da1a20c6a650e8d5227501bfe5a193041c2af47f587e5efb8724f07f6c2
dependencies:
  ansible_core:
    package_pip: ansible-core==2.17.3
  ansible_runner:
    package_pip: ansible-runner==2.4.0
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
