---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:4cb4a485ba1b90630d170ed111342e175b19aa10ba48c9e3045f6026e9049bca
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.5
  ansible_runner:
    package_pip: ansible-runner==2.3.4
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
