---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:5b2158e62d92aebecc6be8f2420bf0535cf8b071ee1d515f9226a125faccfec7
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.2
  ansible_runner:
    package_pip: ansible-runner==2.3.3
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
