---
version: 3
images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:4779c21e12f0350940550f7a00a3398991c43da5624ec7e8041e7290327d4e38
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.0
  ansible_runner:
    package_pip: ansible-runner==2.3.3
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
