---
version: 3

images:
  base_image:
    name: quay.io/jaeichle/ee-minimal-ubi9:latest@sha256:ea0ce6c728ac7ede3c3ba87b4edc0645a0ff365d328aa2e05773cedebf2e4e79
dependencies:
  ansible_core:
    package_pip: ansible-core==2.15.3
  ansible_runner:
    package_pip: ansible-runner==2.3.3
  python_interpreter:
    python_path: "/usr/bin/python3.11"
  galaxy: requirements.yml
  python: requirements.txt

options:
  package_manager_path: /usr/bin/microdnf
