name: REUSE | build and push latest

on:
  workflow_call:
    inputs:
      subdir:
        required: true
        type: string
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  build-and-push-latest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.5.2
    - name: Install ansible-builder
      run: pip install -r requirements.txt
    - name: Build image
      run: cd ${{ inputs.subdir }} ; ansible-builder build -t quay.io/jaeichle/${{ inputs.subdir }}:latest
    - name: Push to quay.io
      uses: redhat-actions/push-to-registry@v2
      with:
        image: quay.io/jaeichle/${{ inputs.subdir }}
        tags: latest
        registry: quay.io/jaeichle
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
