name: REUSE | build and push latest

on:
  workflow_call:
    inputs:
      subdir:
        required: true
        type: string
    secrets:
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true

jobs:
  build-and-push-latest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
    - name: Install ansible-builder
      run: pip install -r requirements.txt
    - name: Create conext
      run: ansible-builder create
      working-directory: ${{ inputs.subdir }}
    - name: Build Image with Buildah
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: ${{ inputs.subdir }}
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./${{ inputs.subdir }}/context/Containerfile
        context: ${{ inputs.subdir }}/context
    - name: Push to quay.io
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/jaeichle
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
