name: ee-darkman-dev | build and push

on:
  push:
    paths:
      - ee-darkman-dev/**
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  call-build-and-push-latest:
    uses: ./.github/workflows/build-latest.yml
    with:
      subdir: ee-darkman-dev
    secrets: inherit
